### ISSUE TITLE
Guide for installation..

### ISSUE THREAD

**Issue by ibnYusrat** [denskop/Dell-Optiplex-755-macOS#1]
Hi..

Can you please provide a guide for using this repository to install macOS on Optiplex. I see the file but I don't know where to start.. I think I have the same config as the one which is supported. But I don't know how to use this repository to begin installation.

**Comment by denskop** [comment]
Hi! Ok, i will add some instructions later to README.md. But at this moment you can do following steps:
1. Open macOS Terminal app
2. Clone this repository:
`git clone https://github.com/denskop/Dell-Optiplex-755-macOS.git`
3. Go to cloned repo:
`cd Dell-Optiplex-755-macOS`
3. Build Clover bootloader for Dell Optiplex 755:
`./Build.sh`
4. Script will ask about your installed CPU: type answer.
5. Next, Clover bootloader you can find at Build folder
`open Build`
6. Install official Clover from pkg to flash drive or hard disk
For example, from this [link](https://github.com/CloverHackyColor/CloverBootloader/releases/download/5100/Clover_v2.5k_r5100.pkg)
7. After installation replace Clover folder at path` EFI -> Clover` to folder from step 4.
8. Good luck!

**Comment by ibnYusrat** [comment]
Thank you very much for the response. I really appriciate it. Do you think these instructions should be added to the README.md also?
